server.servlet.context-path=/sistema/api/v1
server.port=8080
spring.application.name=Microservicios-Spring
spring.jackson.deserialization.fail-on-unknown-properties=true
service.products=list

# Configuracion personalizada de la aplicacion
app.name=Sistema de productos
app.version=1.0.0
app.autor=Desarrollos Inovadores S.A 
app.language=es 
app.country=Mexico

# Configuracion acceso bdd
db.user=rogelio.root
db.password=15dtv0089R